name: CI
on: push
jobs:
  test:
    name: 'Run tests on all packages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn lerna run test
